name: meras
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  auto_direction: ^0.0.5
  firebase_core: ^1.6.0
  firebase_database: ^7.2.2
  firebase_auth: ^3.1.1
  cloud_firestore: ^2.5.2
  provider: ^6.0.0
  intl: ^0.17.0
  image_picker: ^0.8.4+2
  firebase_storage: ^10.0.3
  permission_handler: ^8.1.6
  random_string: ^2.3.1
  mailer: ^5.0.1
  google_sign_in: ^5.0.4
  awesome_notifications:
  firebase_messaging:
  get:
  url_launcher:
  get_storage:
  number_inc_dec: ^0.8.0
  mime: ^1.0.1
  open_file: ^3.2.1
  path_provider: ^2.0.5
  faker: ^2.0.0
  file_picker: ^4.1.6
  flutter_chat_ui: ^1.5.0
  flutter_firebase_chat_core:
  cached_network_image: ^3.2.0
  fluttertoast: ^8.0.8
  photo_view: ^0.13.0
  flutter_native_image: 
  path: 
  flutter_local_notifications: 
  flutter_linkify: 


  #uses-material-design: true
    

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  flutter_auth: ^0.0.1
  flutter_svg: ^0.22.0
  flutter_spinkit: ^5.1.0
  bottom_navy_bar: ^6.0.0
  flutter_rating_bar: ^4.0.0
  rating_dialog: ^2.0.3
  in_app_review: ^2.0.3
  shared_preferences: ^2.0.8
  stripe_payment: ^1.1.4
  fluttericon: ^2.0.0
  http_auth: ^1.0.1
  

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  fonts:
    - family:  MyFlutterApp
      fonts:
       - asset: fonts/MyFlutterApp.ttf

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  assets:
    - assets/images/logo.png
    - assets/images/def.jpg
    - assets/images/main_top.png
    - assets/images/main_bottom.png
    - assets/images/login_bottom.png
    - assets/icons/login.svg
    - assets/icons/SteeringWheel1.png
    - assets/icons/Test1.png
    - assets/icons/TrafficLight1.png
    - assets/icons/Warning1.png
    - assets/icons/X.png
    - assets/images/signup_top.png
    - assets/images/logo1.png
    - assets/images/driver-male.jpg
    - assets/images/Female.png
    - assets/images/trafficsigns.png
    - assets/images/test2.png
    - assets/images/TM.png
    - assets/images/TF.png
    - assets/icons/ringing.png
    - assets/images/req.png
    - assets/images/lavatory.png
    - assets/images/logo_forground.png
    - assets/images/whitelogo.png
    - assets/images/BackgroundProfileLight2.jpeg
    - assets/images/BackgroundProfileDark2.jpeg


  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
